### ISSUE TITLE
Add support for PS 5 DualSense Controller

### ISSUE THREAD

**Issue by Hancho2009** [chrizonix/XInputTest#2]
It would be cool if you add support for the PS 5 DualSense Controller

**Comment by chrizonix** [comment]
Hi @Hancho2009,

The PS5 DualSense Controller is already supported. You just need a tool to connect it to your PC as an Xbox 360 (XInput) device.
You can download this tool here [DS4Windows - ryochan7.github.io](https://ryochan7.github.io/ds4windows-site/).

After you have connected your controller (via Bluetooth or USB), you can activate a profile called "Xbox 360".
After activating this profile, you can use my XInputTest, to test the latency.

Hope this helps!
