### ISSUE TITLE
not working for dualsense controller

### ISSUE THREAD

**Issue by apatton090** [chrizonix/XInputTest#3]
Not recognizing dualsense controller

**Comment by chrizonix** [comment]
Hi @apatton090,

The PS5 DualSense Controller is already supported. You just need a tool to connect it to your PC as an Xbox 360 (XInput) device.
You can download this tool here [DS4Windows - ryochan7.github.io](https://ryochan7.github.io/ds4windows-site/).

After you have connected your controller (via Bluetooth or USB), you can activate a profile called "Xbox 360".
After activating this profile, you can use my XInputTest, to test the latency.

If you want to set the Polling Rate to 1000 Hz (1ms), you can follow my tips here https://github.com/chrizonix/XInputTest/issues/1

Hope this helps!
