### ISSUE TITLE
 MSVCP120.dll and MSVCR120.dll were not found

### ISSUE THREAD

**Issue by humam2104** [chrizonix/XInputTest#5]
I'm having trouble opening the program. It's telling me that one of the libraries is missing.
![image](https://github.com/chrizonix/XInputTest/assets/41898465/3969ae17-2c2d-468b-bf22-5318f876f689)
![image](https://github.com/chrizonix/XInputTest/assets/41898465/8c2c294c-75bd-4491-8f17-d9e8d1190627)

These are the libraries I have installed on the system
![image](https://github.com/chrizonix/XInputTest/assets/41898465/93da1d83-d284-45c6-96f5-fff7b639e5cc)

**Comment by chrizonix** [comment]
Hi @humam2104,

Thanks for the details! Are you using the 32-bit Version of the tool? If so, I can see that you are missing the VC++ Redist 2013 (x86), you just have the VC++ Redist 2013 (x64) installed, maybe this will solve the problem?

Hope this helps :)

**Comment by humam2104** [comment]
It worked! thanks alot!!
